=== serjSavchenko/ROYALFitnessJira/main/xsd/confectionery.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
		targetNamespace="http://www.example.org/confectionery_main" 
		xmlns:tns="http://www.example.org/confectionery_main" 
		elementFormDefault="unqualified">
	<element name="Cakes">
		<complexType>
			<sequence>
				<element name="Order" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="Id" type="positiveInteger"></element>
							<element name="OrderStatus" type="tns:OrderStatus"></element>
							<element name="PaymentType" type="tns:PaymentType"></element>
							<element name="OrderDate" type="date" />
							<element name="DeliveryClient" type="tns:Client" />
							<element name="SendingClient" type="tns:Client" />
							<element name="DeliveryDepartment" type="tns:Department" />
							<element name="SendingDepartment" type="tns:Department" />
							<element name="Product" type="tns:Product" />
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>

	<!-- Order status -->
	<complexType name="OrderStatus">
		<sequence>
			<element name="Id" type="positiveInteger"></element>
			<element name="StatusName" type="tns:OrderStatusValues"></element>
		</sequence>
	</complexType>

	<simpleType name="OrderStatusValues">
		<restriction base="string">
			<enumeration value="Delivered"></enumeration>
			<enumeration value="Processing"></enumeration>
			<enumeration value="Delivering"></enumeration>
			<enumeration value="UnDelivered"></enumeration>
		</restriction>
	</simpleType>

	<!-- Payment Type -->
	<complexType name="PaymentType">
		<sequence>
			<element name="Id" type="positiveInteger"></element>
			<element name="PaymentName" type="tns:PaymentTypeName"></element>
		</sequence>
	</complexType>

	<simpleType name="PaymentTypeName">
		<restriction base="string">
			<enumeration value="Card"></enumeration>
			<enumeration value="Cach"></enumeration>
		</restriction>
	</simpleType>

	<!-- Gender -->
	<complexType name="Gender">
		<sequence>
			<element name="Id" type="positiveInteger"></element>
			<element name="PaymentName" type="tns:GenderNames"></element>
		</sequence>
	</complexType>

	<simpleType name="GenderNames">
		<restriction base="string">
			<enumeration value="Male"></enumeration>
			<enumeration value="Female"></enumeration>
		</restriction>
	</simpleType>

	<!-- Client -->
	<complexType name="Client">
		<sequence>
			<element name="Id" type="positiveInteger"></element>
			<element name="FirstName" type="string"></element>
			<element name="LastName" type="string"></element>
			<element name="Contact">
				<complexType>
					<choice>
						<element name="Email" type="string" />
						<element name="Phone" type="string" />
					</choice>
				</complexType>
			</element>
			<element name="RegistrationDate" type="date" />
			<element name="Discount" type="float"></element>
			<element name="Gender" type="tns:Gender"></element>
		</sequence>
	</complexType>

	<!-- Department -->
	<complexType name="Department">
		<sequence>
			<element name="Id" type="positiveInteger"></element>
			<element name="Name" type="string"></element>
			<element name="City" type="string"></element>
		</sequence>
	</complexType>

	<complexType name="Product">
		<all>
			<element name="Name">
				<simpleType>
					<restriction base="string">
						<maxLength value="256" />
						<pattern value="[a-zA-Z]*" />
					</restriction>
				</simpleType>
			</element>
			<element name="Width" type="float"></element>
			<element name="Height" type="float"></element>
			<element name="Long" type="float"></element>
			<element name="Weight" type="float"></element>
		</all>
	</complexType>
</schema>

=== serjSavchenko/ROYALFitnessJira/main/resources/confectionery_main/confectionery.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Cakes 
	xmlns:tns="http://www.example.org/confectionery_main" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.example.org/confectionery_main confectionery.xsd">
  <Order>
    <Id>1</Id>
    <OrderStatus>
      <Id>1</Id>
      <StatusName>Delivered</StatusName>
    </OrderStatus>
    <PaymentType>
      <Id>1</Id>
      <PaymentName>Card</PaymentName>
    </PaymentType>
    <OrderDate>2001-01-01</OrderDate>
    <DeliveryClient>
      <Id>1</Id>
      <FirstName>FirstName</FirstName>
      <LastName>LastName</LastName>
      <Contact>
        <Email>Email</Email>
      </Contact>
      <RegistrationDate>2001-01-01</RegistrationDate>
      <Discount>0.0</Discount>
      <Gender>
        <Id>1</Id>
        <PaymentName>Male</PaymentName>
      </Gender>
    </DeliveryClient>
    <SendingClient>
      <Id>1</Id>
      <FirstName>FirstName</FirstName>
      <LastName>LastName</LastName>
      <Contact>
        <Email>Email</Email>
      </Contact>
      <RegistrationDate>2001-01-01</RegistrationDate>
      <Discount>0.0</Discount>
      <Gender>
        <Id>1</Id>
        <PaymentName>Male</PaymentName>
      </Gender>
    </SendingClient>
    <DeliveryDepartment>
      <Id>1</Id>
      <Name>Name</Name>
      <City>City</City>
    </DeliveryDepartment>
    <SendingDepartment>
      <Id>1</Id>
      <Name>Name</Name>
      <City>City</City>
    </SendingDepartment>
    <Product>
      <Name>Name</Name>
      <Width>0.0</Width>
      <Height>0.0</Height>
      <Long>0.0</Long>
      <Weight>0.0</Weight>
    </Product>
  </Order>
  <Order>
    <Id>2</Id>
    <OrderStatus>
      <Id>2</Id>
      <StatusName>UnDelivered</StatusName>
    </OrderStatus>
    <PaymentType>
      <Id>2</Id>
      <PaymentName>Cach</PaymentName>
    </PaymentType>
    <OrderDate>2001-01-01</OrderDate>
    <DeliveryClient>
      <Id>2</Id>
      <FirstName>FirstName</FirstName>
      <LastName>LastName</LastName>
      <Contact>
        <Email>Email</Email>
      </Contact>
      <RegistrationDate>2001-01-01</RegistrationDate>
      <Discount>0.0</Discount>
      <Gender>
        <Id>1</Id>
        <PaymentName>Male</PaymentName>
      </Gender>
    </DeliveryClient>
    <SendingClient>
      <Id>2</Id>
      <FirstName>FirstName</FirstName>
      <LastName>LastName</LastName>
      <Contact>
        <Email>"Email@email.com"</Email>
      </Contact>
      <RegistrationDate>2001-01-01</RegistrationDate>
      <Discount>0.0</Discount>
      <Gender>
        <Id>2</Id>
        <PaymentName>Male</PaymentName>
      </Gender>
    </SendingClient>
    <DeliveryDepartment>
      <Id>2</Id>
      <Name>Name</Name>
      <City>City</City>
    </DeliveryDepartment>
    <SendingDepartment>
      <Id>2</Id>
      <Name>Name</Name>
      <City>City</City>
    </SendingDepartment>
    <Product>
      <Name>Name</Name>
      <Width>0.0</Width>
      <Height>0.0</Height>
      <Long>0.0</Long>
      <Weight>0.0</Weight>
    </Product>
  </Order>
</tns:Cakes>
